### ISSUE TITLE
I am getting this error when I try to run GlabTop2-py, How do I deal with it?

### ISSUE THREAD

**Issue by lhy1992** [WilcoTerink/GlabTop2-py#1]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\lib\site-packages\GlabTop2\main.py", line 313, in <module>
    main(sys.argv[1:])
  File "D:\ProgramData\Anaconda3\lib\site-packages\GlabTop2\main.py", line 304, in main
    glabtop.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\GlabTop2\main.py", line 253, in run
    [glacmask, mCells, innerCells] = self.identifyCells(gID)
  File "D:\ProgramData\Anaconda3\lib\site-packages\GlabTop2\main.py", line 102, in identifyCells
    if glacMask[r+1,c+1] == self.mv:
IndexError: index 189 is out of bounds for axis 1 with size 189

Dear WilcoTerink,
I am getting above error when I try to run GlabTop2-py via Anaconda, How do I deal with it?
Or, can you provide some input files that can run glatop2-py successful?
My email address is (hongyuanli@lzb.ac.cn), I will be deeply appreciated that you have done for me and look forward to your reply.
Yours sincerely,
Hongyuan

**Comment by WilcoTerink** [comment]
I have send you some example files with wetransfer. Let me know if that has solved your problem.

**Comment by lhy1992** [comment]
> I have send you some example files with wetransfer. Let me know if that has solved your problem.

I received the input file you provided, and I know what caused this error and made glabtop2-py run successfully. Thank you very much for your help. By the way, I am a learner of the SPHY model. I look forward to learning from you and wish you a happy life.

**Comment by lmeimei20** [comment]
Dear WilcoTerink,
I am also getting this error, can you provide some input files that can run glatop2-py successful?
My email address is (lmeimei@90163.com), I will be deeply appreciated that you have done for me and look forward to your reply. Thanks.
Yours sincerely,

Meimeilin

**Comment by xiaoenli4816** [comment]
> I have send you some example files with wetransfer. Let me know if that has solved your problem.

Dear WilcoTerink,
I am also getting this same error, can you provide some input files that can run glatop2-py successful?
My email address is (xiaoenli4816@gmail.com), I will be deeply appreciated that you have done for me and look forward to your reply. Thanks.
Yours sincerely,
xiaoen

**Comment by xiaoenli4816** [comment]
> > I have send you some example files with wetransfer. Let me know if that has solved your problem.
> 
> I received the input file you provided, and I know what caused this error and made glabtop2-py run successfully. Thank you very much for your help. By the way, I am a learner of the SPHY model. I look forward to learning from you and wish you a happy life.
Hi, could you tell me what the problem is? I got the same error.Thanks,

**Comment by akashbasotra** [comment]
streamlit.runtime.media_file_storage.MediaFileStorageError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/mount/src/glap-top-2_py-new/GlabTop2/app/main.py", line 137, in <module>
    st.image('images/franz_josef.jpg', width=400)#, use_column_width='always')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/runtime/metrics_util.py", line 396, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/elements/image.py", line 165, in image
    marshall_images(
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/elements/image.py", line 534, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/elements/image.py", line 385, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/runtime/media_file_manager.py", line 222, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/runtime/memory_media_file_storage.py", line 116, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/.conda/lib/python3.11/site-packages/streamlit/runtime/memory_media_file_storage.py", line 168, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex

Dear WilcoTerink,
 
I am getting above error when I try to run GlabTop2-py via streamlit app, How do I deal with it?
Or, can you provide some input files that can run glatop2-py successful? and even how to give input file and where we have get output file. so please provide some details regarding this.
My email address is (abasotra44@gmail.com), I will be deeply appreciated that you have done for me and look forward to your reply.
Yours sincerely,
Akash Basotra
